# Generated by Django 5.1.5 on 2025-02-04 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_disciplina', models.CharField(max_length=200)),
                ('codigo', models.CharField(max_length=200)),
                ('descricao', models.TextField(blank=True)),
                ('carga_horaria', models.CharField(choices=[('15h', '15h'), ('20h', '20h'), ('30h', '30h'), ('54h', '54h'), ('60h', '60h'), ('90h', '90h')], max_length=10)),
                ('professor', models.CharField(max_length=200)),
                ('curso', models.CharField(choices=[('C&T', 'C&T')], max_length=10)),
                ('grupo', models.IntegerField()),
                ('dia_da_semana', models.CharField(choices=[('segunda', 'Segunda-feira'), ('terca', 'Terça-feira'), ('quarta', 'Quarta-feira'), ('quinta', 'Quinta-feira'), ('sexta', 'Sexta-feira'), ('sabado', 'Sábado'), ('domingo', 'Domingo')], max_length=10)),
                ('turno', models.CharField(choices=[('MANHA', 'MANHA'), ('TARDE', 'TARDE'), ('NOITE', 'NOITE')], max_length=10)),
            ],
        ),
    ]
