# Generated by Django 5.1.6 on 2025-02-18 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0002_remove_disciplina_codigo"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="disciplina",
            name="dia_da_semana",
        ),
        migrations.AddField(
            model_name="disciplina",
            name="domingo",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="disciplina",
            name="quarta",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="disciplina",
            name="sabado",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="disciplina",
            name="segunda",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="disciplina",
            name="sexta",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="disciplina",
            name="terca",
            field=models.BooleanField(default=False),
        ),
    ]
