# Generated by Django 5.1.6 on 2025-02-18 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0003_remove_disciplina_dia_da_semana_disciplina_domingo_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Analise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ch_total", models.IntegerField(default=2400)),
                ("ch_optativa", models.IntegerField(default=200)),
                ("ch_obrigratoria", models.IntegerField(default=1200)),
                ("ch_concluida", models.IntegerField(default=0)),
            ],
        ),
    ]
