# Generated by Django 5.1.6 on 2025-02-18 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_analise"),
    ]

    operations = [
        migrations.RenameField(
            model_name="analise",
            old_name="ch_obrigratoria",
            new_name="ch_obrigatoria",
        ),
    ]
