# Generated by Django 5.1.6 on 2025-03-23 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_rename_ch_obrigratoria_analise_ch_obrigatoria"),
    ]

    operations = [
        migrations.AddField(
            model_name="disciplina",
            name="cursando",
            field=models.BooleanField(default=False),
        ),
    ]
