#O NOME DOS LINKS

ARCHIVE = '.html'
#NAMES
INDEX = 'index'
LIST = 'list'
DELETE = 'delete'
EDIT = 'edit'
GROUP = 'group'
BASE = 'base'
CH = "carga_horaria"
ADICIONAR_CH = "adicionar_ch"
ATUALIZAR_CH = "atulizar_ch"
#PATHS
PATH_INDEX = INDEX+ARCHIVE
PATH_LIST = LIST+ARCHIVE
PATH_DELETE = DELETE+ARCHIVE
PATH_EDIT = EDIT+ARCHIVE
PATH_GROUP = GROUP + ARCHIVE
PATH_ARCHIVE = BASE + ARCHIVE
PATH_CH = CH + ARCHIVE
PATH_ADICIONAR_CH = ADICIONAR_CH + ARCHIVE
PATH_ATUALIZAR_CH = ATUALIZAR_CH + ARCHIVE
