
ARCHIVE = '.html'
#NAMES
INDEX = 'index'
LIST = 'list'
DELETE = 'delete'
EDIT = 'edit'
#PATHS
PATH_INDEX = INDEX+ARCHIVE
PATH_LIST = LIST+ARCHIVE
PATH_DELETE = DELETE+ARCHIVE
PATH_EDITE = EDIT+ARCHIVE