#O NOME DOS LINKS

ARCHIVE = '.html'
#NAMES
INDEX = 'index'
LIST = 'list'
DELETE = 'delete'
EDIT = 'edit'
GROUP = 'group'
BASE = 'base'
#PATHS
PATH_INDEX = INDEX+ARCHIVE
PATH_LIST = LIST+ARCHIVE
PATH_DELETE = DELETE+ARCHIVE
PATH_EDIT = EDIT+ARCHIVE
PATH_GROUP = GROUP + ARCHIVE
PATH_ARCHIVE = BASE + ARCHIVE